[project]
name = "lego"
version = "0.1.0"
description = "Build scalable, maintainable, performant webapps one block at a time"
authors = [{name = "Karthik Rajgopal"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "python-fasthtml (>=0.12.5,<0.13.0)",
    "monsterui (>=1.0.11,<2.0.0)",
    "email-validator (>=2.2.0,<3.0.0)",
    "pyjwt (>=2.10.1,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
